### ISSUE TITLE
move to rust-lang-nursery and rename?

### ISSUE THREAD

**Issue by BurntSushi** [rust-lang-nursery/stdsimd#11]
@alexcrichton mentioned a bit ago that we might want to move this repo to the nursery. Seems like a good idea to me!

**Comment by BurntSushi** [comment]
In #20, @gnzlbg asks if we should rename the crate.

In my own head, I've always kind of imagined that this crate would add two new top-level modules to `core` named `simd` and `vendor`. The `simd` module would contain the vector types and the various platform independent APIs while the `vendor` module would contain all of the vendor intrinsic functions, with an API that matches the vendor API as closely as possible.

In light of the heavy focus on simd, and because it would be re-exported through the standard library, I haphazardly called this crate `stdsimd`. The most accurate name might be something like `core::{simd, vendor}`, but that's a mouthful.

I honestly don't think there's anything terribly wrong with the current name. Maybe `corevendor` would be better, but that kind of ignores the obvious focus on SIMD.

**Comment by gnzlbg** [comment]
If the objective is to make this be part of `core::` then the actual name does not really matter much right?

**Comment by BurntSushi** [comment]
@gnzlbg Well I think this crate will continue to live in its own repo (like `libc`), so we need something for `rust-lang-nursery/{the_name}`.

**Comment by alexcrichton** [comment]
I'm fine w/ `stdsimd` as the name, I wouldn't feel any pressing need to rename it.

**Comment by alexcrichton** [comment]
Moved!

**Comment by gnzlbg** [comment]
This raised some questions already of the form "isn't this crate only about simd?". If we plan to expose all the intrinsics in `core::vendor` maybe we should just rename the crate to `stdvendor` or `corevendor` as @BurntSushi suggested to make it more discoverable. 

> Maybe corevendor would be better, but that kind of ignores the obvious focus on SIMD.

IIUC only the simd vector types will be in the `simd` module while all of the `simd`-intrinsics will be in the `vendor` module. So I also worry about `corevendor` ignoring the focus on SIMD.

**Comment by BurntSushi** [comment]
I still like the name `stdsimd`. If someone were to describe what we were doing in this repo, I think the obvious explanation is "we're trying to make SIMD work on stable Rust" and that pretty much captures it.
