### ISSUE TITLE
Move away from platform-intrinsic to link_llvm_intrinsic

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang-nursery/stdsimd#112]
The desire of moving away from `platform-intrinsic` to `link_llvm_intrinsic` has been informally discussed, but I am opening this issue to track this as a goal.

All `platform-intrinsics` used are currently in the `simd_llvm` module.

**Comment by BurntSushi** [comment]
When I've said "move away from platform-intrinsic," I've mostly had the specific vendor intrinsics in mind, and in particular, the JSON used to declare the intrinsics.

I'm not aware of the trade offs associated with the custom SIMD intrinsics that Rust exposes.

**Comment by gnzlbg** [comment]
That's how I understood it (I think). That is, remove all dependencies on `platform-intrinsics` here so that we can remove all the JSON/python intrinsic generation from rustc.

**Comment by alexcrichton** [comment]
Hm so now I'm trying to remember why we took this path in the first place... I think it was to provide the intrinsics on stable Rust perhaps so `stdsimd` could be a crate on crates.io? Other than that though I can't recall the precise reason why.

If that's the only reason then I agree it's fine to move to LLVM intrinsics directly because this probably isn't ever going to be on crates.io (but rather included in libstd)

**Comment by gnzlbg** [comment]
I think the idea behind the python binding generators was basically to automatically generate this library from the JSON files and expose it via `platform-intrinsics` instead of having to manually use the `link_llvm_intrinsics`. One could then use those to write a SIMD third-party crate (like @huonw's ), but I don't recall reading anywhere about the next step after doing that (that is, how to get that crate running in rust stable). Maybe the plan was to stabilize the platform intrinsics? Idk.

`link_llvm_intrinsics` has advantages and disadvantages. The biggest advantage is that we can quickly react here to llvm changes without having to change rustc. The largest disadvantage (that we haven't yet ran into) is that, as far as I know, this library only works with whatever LLVM version it is tested, but rustc theoretically support multiple LLVM versions... so... maybe we should start somehow testing those here as well.

**Comment by gnzlbg** [comment]
So I could do this by using a custom derive macro like this:

```rust
#[repr(simd)]
...
#[derive(..., stdsimd_op(Add, Self, Self), stdsimd_op(Sub, Self, Self, ...))]
struct f32x4(...);
```

The question is, do we want to do this?

**Comment by alexcrichton** [comment]
I believe this is finished now except for SIMD-specific operations which we must use intrinsics for (AFAIK), so closing.

**Comment by camelid** [comment]
This line has a TODO that references this issue. Should the TODO be removed?

https://github.com/rust-lang/stdarch/blob/3fa0f6a1316fcb9619d7e002ac4ed78a0c745cef/crates/core_arch/src/simd_llvm.rs#L3

**Comment by Amanieu** [comment]
Probably yes.
