### ISSUE TITLE
Rust support for nontemporal stores?

### ISSUE THREAD

**Issue by nominolo** [rust-lang-nursery/stdsimd#114]
The `_mm_stream_ps` intrinsic implements a store to memory with a "non-temporal" hint (i.e., try not to pollute the cache). In the LLVM code this is implemented via `__builtin_nontemporal_store` which should compile to an LLIR `store` instruction with hint `!nontemporal`. e.g., something like:

```
store <8 x i64> %{{.*}}, <8 x i64>* %{{.*}}, align 64, !nontemporal
```

Is there a way to generate this in Rust, or do we need add this to the compiler first?

See also:
- [`store` instruction docs](https://llvm.org/docs/LangRef.html#store-instruction)
- [a related LLVM change](https://reviews.llvm.org/D21272)

**Comment by alexcrichton** [comment]
Ah yeah I believe we'll need to add support upstream for such an intrinsic, I don't think we can do this with rustc as-is today

**Comment by alexcrichton** [comment]
I've opened up an [upstream PR](https://github.com/rust-lang/rust/pull/45367) to add this support to rustc

**Comment by alexcrichton** [comment]
Ok! Took awhile but the support is now upstream as an unstable intrinsic!
