### ISSUE TITLE
API for constants in vendor interface

### ISSUE THREAD

**Issue by BurntSushi** [rust-lang-nursery/stdsimd#14]
Some vendor intrinsics come with [various constants defined](https://github.com/llvm-mirror/clang/blob/dcd8d797b20291f1a6b3e0ddda085aa2bbb382a8/lib/Headers/smmintrin.h#L1587-L1590) that give special meaning to integer values. The `_SIDD_*` constants, for example, are used with the [packed compare](https://github.com/llvm-mirror/clang/blob/dcd8d797b20291f1a6b3e0ddda085aa2bbb382a8/lib/Headers/smmintrin.h#L1659) intrinsics.

What should we do about these? Should we define them at all? If we do, should they go in their own separate module, or should they live in the same flat namespace as the rest of the intrinsic functions?

**Comment by gnzlbg** [comment]
> Should we define them at all?

Yes.

> If we do, should they go in their own separate module, or should they live in the same flat namespace as the rest of the intrinsic functions?

Right now they live in the same module, which is what the C API does (and any "nicer" solution won't be what C does).

Having said this, there aren't that many constants, so we could put them in their own modules.

Currently we are basically dumping everything in the `vendor` module, so this is at least tangentially related to: how "clean" do we want `vendor` to be? The answer to this question doesn't need to be the same for all architectures.

**Comment by alexcrichton** [comment]
I'm gonna close this now due to https://github.com/rust-lang-nursery/stdsimd/issues/263
