### ISSUE TITLE
next release?

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang-nursery/stdsimd#142]
I'd like to be able to use `stdsimd` via crates.io, at least until it becomes part of core which might take a while. 

I've updated the readme and Cargo.toml in #141 but since we added the crate `stdsimd-test` that would need to be released as well. 

@alexcrichton is there a way to release `stdsimd` on crates.io without releasing `stdsimd-test` ?

@BurntSushi would you be able to prepare a release in the near future ? The API has changed to `unsafe`, and there have been many other smaller changes since version `0.0.2` that i'd like to use.

**Comment by BurntSushi** [comment]
Yeah I think the accepted solution here w.r.t. to `stdsimd-test` is to just remove the dep from the `Cargo.toml` before publishing. I wouldn't mind publishing `stdsimd-test` on principle, but it has dependencies on git repositories. @dtolnay Would it be possible to push out new releases of `quote` and `syn`? If not, it's not a big deal and I can just hack a new release of `stdsimd` on to crates.io.

**Comment by alexcrichton** [comment]
Agreed on just commenting out stdsimd-test! (I don't think we should publish that)

**Comment by alexcrichton** [comment]
@BurntSushi mind adding me with the ability to publish?

**Comment by BurntSushi** [comment]
@alexcrichton Done! I added both you and the libs team. Should have done that a while ago. :-)

**Comment by alexcrichton** [comment]
Ok, 0.0.3 published!

**Comment by gnzlbg** [comment]
awesome thanks!
