### ISSUE TITLE
codegen tests

### ISSUE THREAD

**Issue by BurntSushi** [rust-lang-nursery/stdsimd#15]
I suspect the most critical aspect of implementing vendor intrinsics is making sure you write the implementation such that the desired CPU instruction is generated. For this, we should come up with a simple way of writing codegen tests.

IIRC, the Rust compiler itself has a way to run codegen tests, so we might learn something about doing this by looking at `rustc`.

**Comment by BurntSushi** [comment]
@alexcrichton @gnzlbg Do you have any thoughts on the best way to do this? If possible, I'd really like to try to get this setup sooner rather than later so that we can accrue codegen tests as we add new intrinsics.

**Comment by gnzlbg** [comment]
@BurntSushi [bitintr](https://github.com/gnzlbg/bitintr) does it as follows.

- 1. It has an `asm/` folder containing the code-gen tests:
  - 1.1 Each test is composed of two files:
    - the rust code to test in an `.rs` file
    - the assembly that it should generate in an `.asm` file
  - 1.2 The test name encodes the architecture and the backend feature name:
    - `arch_feature_testname.rs` + `arch_feature_testname.asm`
    - For example, [`x86_bmi2_mulx.rs`](https://github.com/gnzlbg/bitintr/blob/master/asm/x86_bmi2_mulx.rs) and [`x86_bmi2_mulx.asm`](https://github.com/gnzlbg/bitintr/blob/master/asm/x86_bmi2_mulx.asm) are used to check that the `mulx` CPU instruction is generated for x86 when the `bmi2` feature is enabled.
- 2. It has a python script [`check_asm.py`](https://github.com/gnzlbg/bitintr/blob/master/check_asm.py) that:
  - [finds all the files in the asm folder](https://github.com/gnzlbg/bitintr/blob/master/check_asm.py)
  - [parses the architecture, feature, and name of each test](https://github.com/gnzlbg/bitintr/blob/master/check_asm.py#L25)
  - [compiles the files and diffs the generated assembly output against the reference](https://github.com/gnzlbg/bitintr/blob/master/check_asm.py#L112) ([this is how the cargo command is build for each Rust file](https://github.com/gnzlbg/bitintr/blob/master/check_asm.py#L57)
- 3. It uses cross-compilation to test X86 and ARM from the same host. I didn't had the need to support other platforms but I don't see why it could be hard to do so. It originally also compared the LLVM IR produced against an `_ir.ll` file, but I did not find this useful (the code to do this is still in the script though, I could clean that up). The `asm/` directory is hardcoded in the script, but it would be trivial to make it an argument. 

Feel free to use it if it can help you and let me know if you have any questions, but the script is fairly trivial.

**Comment by gnzlbg** [comment]
@BurntSushi The whole purpose of the `bitintr` library was to guarantee that the right instructions are generated when the host support those. FWIW, this "system" discovered a couple of bugs in the library and LLVM. 

If the whole purpose of a library is to guarantee a certain code-gen, then that's what you should be testing. The system I came up with in half an hour is probably not the best way to do it, but _any_ testing trumps no testing.

**Comment by BurntSushi** [comment]
@gnzlbg Ah that's awesome, thanks. I'll check it out and try to get something added to this repo. But yeah, I also imagine the bitintr intrinsics will want to get added to this repo as well, and regressing on tests wouldn't be nice. :-)

**Comment by gnzlbg** [comment]
> But yeah, I also imagine the bitintr intrinsics will want to get added to this repo as well,

What do you mean? To add those intrinsics to this repo?

**Comment by BurntSushi** [comment]
@gnzlbg Well, I assume you want to be able to use them on Rust stable, and the whole point of this repo is that it should eventually get distributed and exported via the standard library. For example, we should grow a `src/x86/bmi2.rs` file which contains the intrinsics exported here: https://github.com/llvm-mirror/clang/blob/master/lib/Headers/bmi2intrin.h You would then use the intrinsics from this crate (which should eventually be in `core::vendor` or whatever) instead of [using `platform-intrinsics`](https://github.com/gnzlbg/bitintr/blob/master/src/x86/intrinsics/bmi2/bzhi.rs#L9-L13).

**Comment by BurntSushi** [comment]
(The hope is that this crate continues to live in its own repo like `libc` so that it's easy to contribute to and add intrinsics, but is ultimately part of `core`. @alexcrichton Do I have that right?)

**Comment by gnzlbg** [comment]
@BurntSushi I see, that makes sense. I thought that this repo was only about SIMD intrinsics.

I could contribute the BMI, BMI2, and ARM intrinsics of bitintr that need compiler support if there is interest, but maybe we could chat about this or discuss it somewhere else to not trash this issue with it.

**Comment by BurntSushi** [comment]
@gnzlbg Yeah sure feel free to open a new issue.

I used the word "simd" because most of the intrinsics are operations on vector, but it's not the most accurate term since the intent is to cover as many vendor intrinsics as we can. Putting aside the SIMD vector types, there's really nothing SIMD specific about our strategy with getting the vendor intrinsics to work on stable Rust.

**Comment by alexcrichton** [comment]
The script @gnzlbg mentioned looks great! I'm always personally preferable to write everything in Rust and get a pure `cargo test` to be sufficient to check everything, but whatever works here should be fine.

@BurntSushi also indeed! Adding this crate to part of `core` one day seems quite feasible to me. It'll require gymnastics eventually but we'll deal with that when we get there.

**Comment by BurntSushi** [comment]
@gnzlbg With respect to your testing setup, I notice that you're checking the entire assembly of a function. Is there a specific reason for doing that as opposed to just checking for the generation of a specific instruction or even checking the llvm IR instead? (I don't have any specific objections, but would like to learn.)

And yeah I agree with @alexcrichton in that I'd like to eventually get this jiggered into `cargo test` somehow but we don't need to start there!

**Comment by gnzlbg** [comment]
> Is there a specific reason for doing that as opposed to just checking for the generation of a specific instruction

Not really, it just evolved this way. At the beginning, I just wanted to observe the assembly manually, and then when I wanted to ensure that it did not change doing a diff of the whole assembly solved the problem. There are definetely ways to improve this.

> checking the llvm IR instead?

The LLVM IR changes more than the assembly does, and I decided to focus on the assembly because that is, at the end of the day, what matters. If the code doesn't generate the proper assembly then there is a bug in the library, rustc, llvm, etc. 

> I'd like to eventually get this jiggered into cargo test

That would be great. IMO diffing the LLVM IR or just a single instruction instead of the whole assembly is just a tiny improvement. A significant improvement would be to not have to write the codegen tests in the first place. Ideally, we would just have a procedural macro like this:

```rust
#[stdsimd_check("imulq")]
#[inline(always)]
#[target_feature = "+bmi2"]
pub fn _mulx_u32(a: u32, b: u32) -> (u32, u32) {
    let result: u64 = (a as u64) * (b as u64);
    let hi = (result >> 32) as u32;
    (result as u32, hi)
}

#[stdsimd_check("imulx")]
#[inline(always)]
#[target_feature = "+bmi2"]
pub fn _mulx_u64(a: u64, b: u64) -> (u64, u64) {
    let result: u128 = (a as u128) * (b as u128);
    let hi = (result >> 64) as u64;
    (result as u64, hi)
}
```

that under some feature flag generates the tests for us.

**Comment by alexcrichton** [comment]
> Ideally, we would just have a procedural macro like this:

That's... awesome! I'm gonna see if I can't whip up a test that does that.

**Comment by alexcrichton** [comment]
https://github.com/BurntSushi/stdsimd/pull/28

**Comment by alexcrichton** [comment]
Tests added!
