### ISSUE TITLE
AVX detection needs to check if OS supports save/restore

### ISSUE THREAD

**Issue by jrmuizel** [rust-lang-nursery/stdsimd#153]
See https://hg.mozilla.org/mozilla-central/file/64bab5cbb9b6/mozglue/build/SSE.cpp#l190 for an example

**Comment by BurntSushi** [comment]
Why? Can you provide additional context or a link to Intel docs?

**Comment by nominolo** [comment]
I'm guessing if the OS isn't AVX enabled, then context switching might only save and restore part of the registers.

**Comment by jrmuizel** [comment]
Yep. https://software.intel.com/en-us/blogs/2011/04/14/is-avx-enabled

**Comment by petrochenkov** [comment]
@BurntSushi 
Code in https://hg.mozilla.org/mozilla-central/file/64bab5cbb9b6/mozglue/build/SSE.cpp#l190 uses logic from Intel SDM Volume 1, Chapter 14.3 Detection of AVX instructions.
Technically, if the "OS support" bits (`xgetbv(0) & AVX_STATE` from the link) are disabled, then AVX instructions will just generate #UD exceptions.

**Comment by gnzlbg** [comment]
@jrmuizel do you have a small testcase that currently breaks because of this? I'd like to add it to the test suite, run-time feature detection is "minimally" tested.

**Comment by gnzlbg** [comment]
Which extension need xsave? only avx? probably AVX2 and AVX512 need this as well right?

**Comment by jrmuizel** [comment]
I don't really have a testcase because you need to run on a platform that doesn't support saving the ymm registers like Windows XP. Any extensions that use registers larger than the xmm ones will need to check for OS support.

**Comment by gnzlbg** [comment]
Note that AFAIK Rust doesn't support Windows XP anymore, but I've submitted a PR with the fix in case you want to review it. I've required XSAVE and OSXSAVE for AVX and AVX2 support (and will update this once we add AVX-512 support).
