### ISSUE TITLE
List of intrinsics that are always available

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang-nursery/stdsimd#164]
Some of the intrinsics provided by `stdsimd` are available on all CPUs of a particular architecture. We keep track of them here, and might one day add this to their docs. 

# `x86/x86_64`

- [ ] `i386`: everything in this module should always be available.
- [ ] `EFLAGS`: `__readeflags`, `__writeeflags`.

# `ArmV6`

- [ ] `_rev_u16`
- [ ] `_rev_u32`

**Comment by alexcrichton** [comment]
I'd personally prefer to stick with "unsafe everywhere" as it's easy to not make a mistake, it's just always the same thing!

**Comment by gnzlbg** [comment]
Yes, I am not 100% sure, but I tend to agree. 

What worried me is that people might want to do run-time detection on these, but since they are always available, there is nothing to detect. So I opened this issue to keep track of the ones that are always available, with the aim of one day, maybe adding this information to the docs.
