### ISSUE TITLE
Make the `xsave` target feature available on x86 in rust nightly

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang-nursery/stdsimd#167]
This is required to use the xgetbv instruction, which is required to detect, amongst others, AVX support. I am not proposing to add this to the list of features we want to stabilize, but I think we should add this to rustc even if we only end up using it internally in `stdsimd`.

**Comment by alexcrichton** [comment]
I think this was since fixed, right?

**Comment by gnzlbg** [comment]
Yes.
