### ISSUE TITLE
CI Full QEMU emulation of ARM (and CI of missing architectures)

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang-nursery/stdsimd#176]
For run-time feature detection on ARM user-space QEMU is not enough (because it doesn't emulate `/proc/cpuinfo`, `auxv`, ...). This blocks implementing the ARM NEON intrinsics because we can't use `simd_test` on them, so it is a pretty big blocker:

- [ ] we need to add full QEMU emulation for the ARM build bots that we have

We also need to add Android and iOS build-bots because run-time feature detection there works a bit differently. 

At this point we will be very close to reimplementing most of libc's ci infrastructure... Ideally we should also add emscripten, MIPS, PowerPC, and Sparc64 build bots sooner rather than later.

Since CI is currently a big blocker for progress, and getting this right will pay off, does somebody with experience on this volunteers? I have already started to give this a try but my progress has been really slow.

**Comment by alexcrichton** [comment]
The infrastructure in the libc repo will probably never reach the point where it can be easily shared, so I think it's fine to just duplicate various portions.

**Comment by lu-zero** [comment]
For PowerPC I think @edelsohn might help.

**Comment by edelsohn** [comment]
If the question is access to systems to run CI for PowerPC, one can request free VMs to host Open Source projects at OSUOSL

http://osuosl.org/services/powerdev/

or Unicamp

http://openpower.ic.unicamp.br/minicloud/

**Comment by gnzlbg** [comment]
The short term plan was to use `cross`' `qemu-system` support on travis Linux boxes to emulate powerpc targets (see [here](https://github.com/japaric/cross/pull/166)).

But I would prefer to set up testing for one of those PowerPC boxes since some of them come with NVIDIA GPUs and we could use them to test the NVPTX backend as well (which is something we can't do with qemu).

**Comment by gnzlbg** [comment]
qemu-user supports auxiliary vectors and run-time feature detection prefers these over `cpuinfo` - since auxiliary vectors are already tested on CI I am closing this.
