### ISSUE TITLE
document the vector types and their methods

### ISSUE THREAD

**Issue by BurntSushi** [rust-lang-nursery/stdsimd#19]
The various [vector types](https://docs.rs/stdsimd/0.0.2/stdsimd/simd/index.html) are largely undocumented at this moment in time. Each type should get documentation along with each method. My hope is that we can find a way to write the docs for one type/set of methods, and have that apply to the rest via macros.

**Comment by gnzlbg** [comment]
All vector types and their methods are already documented.
