### ISSUE TITLE
Should we use `std` by default?

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang-nursery/stdsimd#193]
Currently `std` is an opt-in feature, should we add it to the default features of the crate?

**Comment by BurntSushi** [comment]
Yes. AFAIK, this is what everyone (that supports `no_std` and `std`) does. `std` by default, where `no_std` is opt-in.

**Comment by gnzlbg** [comment]
Ok, I'll send a PR.

**Comment by gnzlbg** [comment]
Now `stdsimd` does always require `std`, while those in `core` can use `coresimd` instead, which is unconditionally `no_std`.
