### ISSUE TITLE
Adding bit manipulation intrinsics:

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang-nursery/stdsimd#20]
I could add the bit manipulation intrinsics from the `bitintr` library to this one. I have two questions:

- [ ] IIUC the intrinsics here should be marked with `#[target_feature]` and be unsafe, that is, they are guaranteed to generate the right CPU instructions on the targets that support a feature. Portability is left to third-party crates, is this correct? 
- [ ] Given the organization in this crate, I would be adding the following modules (do they make sense?):
    - `x86::{bmi1, bmi2, abm, tbm}`
    - `arm::{v5, v6, v7, v8}`
- [ ] Should the crate be renamed to something else?

**Comment by alexcrichton** [comment]
@gnzlbg is this issue mostly done now?

**Comment by gnzlbg** [comment]
Yes, this is finished.
