### ISSUE TITLE
Adding minimal run-time feature detection

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang-nursery/stdsimd#22]
If this crate is going to be moved into the nursery it might make sense to prototype run-time feature detection directly here, maybe as a branch. This is a pre-RFC, I don't think it makes much sense to submit an RFC till we have a particular solution to show.

# Pinging relevant people

- @gz and @shepmaster have written very comprehensive cpuid libraries in pure rust
- @BurntSushi @parched @alexcrichton

# Purpose

As opposed to @gz and @shepmaster libraries which aim to be comprehensive, run-time feature for `std`:

- only needs to detect the target features that are stabilized or on the road to stabilization. In the near future this means x86's SIMD and BMI1/2/ABM/TBM features, and ARM's Neon and RBIT. 
- be zero cost, that is, if you don't use it you don't pay for it:
  - I think we can get away with a small global variable using `lazy_static!` since this will only be initialized if it is actually accessed
- be performant:
  - x86: use `cpuid` instruction to read the flags required to detect the supported features
  - arm: detecting features require privileged mode, so we probably need to detect privileged mode, and if not (which is the common case), we might only be able to support this on certain platforms (e.g. fetch and parse /proc/cpuinfo), this is not as cheap as on x86 but one only needs to do this once.

# API 

The RFC proposes to use a stringly-typed API but leaves the exact proposal to a future RFC. I think that we should use a macro to be able to resolve features at compile-time using `#[cfg(target_feature)]`, and only if that resolves to false execute the run-time feature detection. I think this is a good API, the macro could map the string to enum values, so that the run-time feature detection could use enums internally and avoid any string parsing.

**Comment by alexcrichton** [comment]
This seems like a fine thing to prototype in this crate! I agree we probably don't need to pull in more full-featured libraries, just keep it targeted to the use case here and prepare it for eventual inclusion into libcore (e.g. reducing deps as much as possible). 

Having detection primarily runs through a macro seems like a great idea, something like:

```rust
if cfg_feature_enabled!("foo") {
    // ..
}

// implemented as

macro_rules! cfg_feature_enabled {
    ($name:tt) => (cfg!(target_feature = $tt) || $crate::__unstable_detect_feature($tt))
}
```

(or something like that)

We can probably keep the actual function hidden for now.

**Comment by BurntSushi** [comment]
Sounds great to me!

**Comment by shepmaster** [comment]
> As opposed to @gz and @shepmaster libraries

Can you expand on why you say "opposed to" when talking about [cupid](https://github.com/shepmaster/cupid)?

**Comment by gnzlbg** [comment]
@shepmaster cupid identifies most cpu features, the cpu model, cache line information, etc. 

On x86, we just need to be able to identify `sse`, `sse2`, `sse3`, `sse4.1`, `sse4.2`, `avx`, `avx2`, `abm`, `lzcnt`, `popcnt`, `bmi`, `bmi2`, and `tbm` for now. 

We could reuse `cupid` initially for this, but the idea is to make this part of `core::vendor`, so we probably want to strip `cpuid` down as much as possible. And if possible, do the detection with a single call to the `cpuid` instruction. 

Does that make sense?

**Comment by gnzlbg** [comment]
So I've initial support in https://github.com/BurntSushi/stdsimd/pull/31 .It is based on @gz and @shepmaster libraries so kudos to them. Where should I document this attribution?

It doesn't handle ARM at all. Clang and GCC can only do compile-time feature detection support for ARM, because doing it at run-time requires privileged mode. I think that for detecting NEON we can start with forwarding it to compile-time support. If there is interest on run-time detection support for NEON, we could do that by querying the platforms' equivalent of `proc/cpuinfo`.

**Comment by shepmaster** [comment]
I strongly disagree with rewriting libraries like this, but I can see that the decision has already been made by the community.

**Comment by gz** [comment]
@shepmaster Why do you disagree?
@gnzlbg No need to bother with attribution for me for this, I think the inventive value of the code is quite low ;-)

**Comment by gnzlbg** [comment]
@shepmaster I'd say it's rather a different library. For the features I cared about I read the source code of both your libraries, the C libcpuid library, and the reference manuals from Intel and AMD. This resulted in one feature request/bug reported to the cupid library (which I think is a win for everybody). I also found some inconsistencies with respect to popcnt / lzcnt / abm that AFAICT none of the libraries handle properly. If I figure out a way to handle this properly I'll fill issues that I think will hopefully benefit everybody. 

I also thought to start by using one of the libraries internally, but a >2kLOC each they are a bit of a hammer for the problem run-time feature detection in rust core is attempting to solve. 

If we decide that we would like to have full-blown cpuid support in the std library, I think that using one of the existing libraries would be the best path forward.

**Comment by shepmaster** [comment]
> No need to bother with attribution for me for this

Same for me.

----

> Why do you disagree?

Because it needlessly fragments the ecosystem. Now there will be one more thing that tests something slightly different

> but a >2kLOC each

That's not a problem with a statically compiled language, and we already bring in all of LLVM.

> e.g. reducing deps as much as possible

Didn't we perform a **huge** amount of work to rewrite how Rust is built purely to allow for crates to be used inside the compiler proper? Why eschew that?

----

> I also found some inconsistencies with respect to popcnt / lzcnt / abm that AFAICT none of the libraries handle properly

I can't speak for @gz, but I'd certainly have appreciated a bug being filed so that anyone besides yourself knew about it and might have had a chance to fix it.

----

Let me state clearly: **I do not believe I can change anyone's opinion on this matter** and I fully expect that you will go forward as planned. I just don't fully understand why I was brought into a discussion that started with "you wrote this thing that we aren't going to use". It makes me grumpy,
 thus the tone of my replies.

Libraries are *supposed* to grow to meet the needs of their users. If cupid does too much or too little, I *want to know about it*. Basically, I was told at T=0 "it doesn't do exactly what I want" and at T=1day I was told "I rewrote it because it didn't do what I want". It just makes me feel like it's pointless to create the library in the first place. 

I fully admit to feeling hurt from this, and I understand programmers don't like dealing with emotions, so feel free to ignore everything I've said.

**Comment by gnzlbg** [comment]
> Libraries are supposed to grow to meet the needs of their users. If cupid does too much or too little, I want to know about it. Basically, I was told at T=0 "it doesn't do exactly what I want" and at T=1day I was told "I rewrote it because it didn't do what I want". It just makes me feel like it's pointless to create the library in the first place.

Sorry it came out this way. I pinged you both here because you both have written cpuid libraries before and I wanted your input. 

The background of all of this is in this RFC: https://github.com/rust-lang/rfcs/pull/2045
The relevant part of it is that using a target feature at run-time on a host that does not support it is undefined behavior. The discussion moved in the direction that if run-time feature detection is required for correctness, then we should provide it in std or core, at least for the features that are going to make it into rust stable. 

> I do not believe I can change anyone's opinion on this matter

So that's basically the only thing that is more or less clear: we want something for this in std or core. We haven't decided an API yet, nor whether we roll a custom solution, or use a third party library, or even LLVM's compiler-rt cpuid library which rustc is already shipping.

I wrote that PR because I wanted to play with an API so that I have something more concrete for the target feature RFC, but all doors are still open. If you think we are making a mistake, please speak up! That's the main reason I pinged you. 

> It just makes me feel like it's pointless to create the library in the first place.

Both cupid and rust-cpuid are great and extremely comprehensive.

Wanting something minimal was _my_ desire, but probably others disagree with it and I don't know what the right solution for this is. 

---

> I can't speak for @gz, but I'd certainly have appreciated a bug being filed so that anyone besides yourself knew about it and might have had a chance to fix it.

[I did fill that bug](https://github.com/shepmaster/cupid/issues/7), but it is missing that lzcnt on some AMD processors also denotes popcnt. I really don't know what's the right thing to do there though.

**Comment by shepmaster** [comment]
> but it is missing that lzcnt on some AMD processors also denotes popcnt

Ah yes, the way the bug is filed make me think it was a request for enhancement, not that the current library does something *wrong*. I've updated my labels.

**Comment by gnzlbg** [comment]
@BurntSushi The PR of run-time feature detection is currently un-tested. I have thought a bit about how to test it, and I think the best thing to do would be:

- add @shepmaster and @gz libraries as dev dependencies
- use them to detect the CPU target features
- compare our results against theirs

The advantage of this is that this allows us to test the library on all x86 hosts. The only way to fully test this would be to run these tests on a bunch of different CPUs though. 

Thoughts?

**Comment by alexcrichton** [comment]
Sounds like a good idea to me!

**Comment by alexcrichton** [comment]
Done in https://github.com/rust-lang-nursery/stdsimd/pull/31!
