### ISSUE TITLE
Find a way to test auxv on Linux

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang-nursery/stdsimd#234]
Ideally we should add some synthetic tests like the ones for cpuinfo that works on all platforms. The auxv crate has some of them here: https://bitbucket.org/marshallpierce/rust-auxv/src/8d07bcd24d72f35ab3a610fb022dc5988a9ce210/src/test-data/?at=master (@marshallpierce)

but none of them are for ARM or PowerPC which are the only platforms were we currently use auxv.

**Comment by marshallpierce** [comment]
I added a procfs auxv file from my raspberry pi 3 to that repo, so now there's at least an arm sample.

**Comment by gnzlbg** [comment]
Nice! That is very helpful! As a rough sketch of what we could initially do, how does the following sound?:

- [ ] add the `auxv` crate as a dev-dependency and test that our implementation produces the same results as the `auxv` crate on all the platforms that we are currently testing
- [ ] test directly against some or all of the `auxv` dumps of the `auxv` crate (I don't know the best way to set this up, but worst case we can just copy the files here)
- [ ] generate dumps of `auxv` for other platforms that we care about and commit them to the `auxv` crate upstream

**Comment by marshallpierce** [comment]
Sounds good to me!

**Comment by gnzlbg** [comment]
This has already been fixed on master. We test run-time detection against the `auxv` crate and some processor dumps for ARM, Aarch64, and PowerPC.
