### ISSUE TITLE
Query number of lanes of a SIMD vector type

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang-nursery/stdsimd#236]
Should we add a way to programmatically query the number of lanes of a SIMD vector type? 

If so, 

- should we use an associated function or an associated `const`?
- how should we name it?

**Comment by gnzlbg** [comment]
The `f32x8::len` associated function landed on master, we should either resolve this issue or remove it before the next release.

**Comment by BurntSushi** [comment]
What is the use case for a `len` method?

**Comment by gnzlbg** [comment]
The only situation in which I wanted it was to iterate over the lanes of a SIMD vector via a type alias:

```rust
type fvec = f32x8;
for i in 0..fvec::len() {
    v.store(i, ...)
}
```

That way if I later change the vector type to `f32x16;` the loop remains correct.

If use `0..8` I would need to keep the trip count and the vector type in sync.

**Comment by gnzlbg** [comment]
Having said this, I think that a `::LANES` associated const would be a better fit, and I acknowledge that writing a loop over the lanes is not good style, but sometimes necessary to write portable fallback implementations of some SIMD operations that work on the portable vector types.

**Comment by BurntSushi** [comment]
I feel like we should not have this unless there is a more compelling use case.

**Comment by gnzlbg** [comment]
There is a discussion about adding the size and align of the integer types as associated const of those types, so that you can write `i32::SIZE` instead of `::std::mem::size_of::<i32>()`. In some contrived sense, this is similar to that, but I agree that at least my use case isn't very compelling, and I can achieve the same by just implementing a trait for the simd types externally (as in, this doesn't need to be part of `stdsimd`).

**Comment by parched** [comment]
FWIW an associated function would scale better to runtime-sized SIMD vectors like Arm SVE.

**Comment by AdamNiederer** [comment]
I've received a few requests to implement this in faster, mainly for performing reductive operations over a vector. I didnt't want to add it there because it could cause people to write non-portable code, but because that isn't a goal of stdsimd (afaik) I don't see any reason to not add it.

**Comment by gnzlbg** [comment]
I've renamed this to `Self::lanes() -> usize` in the portable vector types API rework, and have found it extremely useful when implementing the rest of the API. 

@parched 

> FWIW an associated function would scale better to runtime-sized SIMD vectors like Arm SVE.

I think we shouldn't try to create an API for both packed and scalable vector types. We should try to be consistent with naming, but these two APIs are different enough that I personally consider them to be orthogonal. 

That is, we should pursue an API for packed SIMD types that stands on its own first, followed by pursuing architecture-specific APIs for scalable vector types (ARM, RISCV, ..).

Pursuing a portable API for scalable vector types is pretty much an open research problem at this point in time, and trying to come up with a portable API that works for both is another open research problem whose solution necessarily must come afterwards.

**Comment by gnzlbg** [comment]
I'm closing this, the RFC proposes to use `lanes()` here and nobody has complained there. If you have an opinion about this, speak up in the RFC PR: https://github.com/rust-lang/rfcs/pull/2366
