### ISSUE TITLE
x86_64-unknown-linux-gnu fails on travis (for no apparent reason)

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang-nursery/stdsimd#241]
In the previous commit both `x86_64-unknown-linux-gnu` and `i586-unknown-linux-gnu` were failing for no apparent reason. I tried restarting them without any luck (that commit adds the powerpc build bots but otherwise changes nothing else and the PR builds were green). The travis build just fails in the middle of running the test, no error, no segfault, no output, no nothing. It just stops and the build is marked as "failed".

The last commit only changed formatting and magically fixed the `i586-unknown-linux-gnu` build but `x86_64-unknown-linux-gnu` is still failing after 3 minutes without any reason. Restarting does not help here either. 

Any idea of what is going on? Am I going crazy?

**Comment by alexcrichton** [comment]
I think this was fixed by [this](https://github.com/rust-lang-nursery/stdsimd/blob/4022efe0817e8486f710b57afaaaf3077af4cca8/.travis.yml#L45-L46)

**Comment by gnzlbg** [comment]
I haven't noticed it lately so it looks fixed.
