### ISSUE TITLE
x86::tbm::bextri triggers an LLVM codegen error

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang-nursery/stdsimd#26]
It is the only instruction not implemented from the TBM feature set.

**Comment by gnzlbg** [comment]
@alexcrichton @BurntSushi the root of the issue is that `tbm::bextri` takes an argument (`u32`/`u64`) that must be _immediate_. Lucky for us, only the first 16 bits of this value matter. Unlucky for us, using a `constify_imm16`, with a `match` statement containing 65543 arms, makes the `stdsimd` crate take between forever and never to compile 😆 

Thoughts?

**Comment by alexcrichton** [comment]
I'd probably just leave this open for now, I'm not sure how we'd fix it :(

**Comment by alexcrichton** [comment]
I'm gonna close this in favor of https://github.com/rust-lang-nursery/stdsimd/issues/248 as I believe they're basically the same issue.
