### ISSUE TITLE
load[_unchecked] and store[_unchecked] take an unnecessary offset parameter

### ISSUE THREAD

**Issue by Vurich** [rust-lang-nursery/stdsimd#272]
Currently `load`, `load_unchecked`, `store` and `store_unchecked` essentially reimplement slicing logic with their `offset` parameter. They could instead take only one parameter (the slice) and have the user replace:

```rust
u32s::load(my_slice, n)
```

with

```rust
u32s::load(&my_slice[n..])
```

I believe there is no downside to doing this other than the fact that it would require a major version bump (although every version bump is major right now).

**Comment by gnzlbg** [comment]
I ran into this while reworking the portable vector types API and decided to drop the offset parameter.

**Comment by gnzlbg** [comment]
This was fixed in #338 .
