### ISSUE TITLE
OSX CI is failing

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang-nursery/stdsimd#278]
Since https://github.com/rust-lang-nursery/stdsimd/commit/6ef0ae27aaa087b97b9482f22eaf8c9ed6cf9853 OSX CI has [started failing](https://travis-ci.org/rust-lang-nursery/stdsimd/builds/327753982) with a message like:

```
test x86::i686::sse::tests::test_mm_cvtpi16_ps ... error: process didn't exit successfully: `/Users/travis/build/rust-lang-nursery/stdsimd/target/x86_64-apple-darwin/debug/deps/coresimd-c133463bafacabd8` (signal: 4, SIGILL: illegal instruction)
```

The commit in question did indeed change things around that function... but I have no idea how it was a functional change...

@gnzlbg mind double-checking my double-checking? Would be good to have another set of eyes on this!

**Comment by gnzlbg** [comment]
I tried to reproduce it without any luck. 

> but I have no idea how it was a functional change...

That commit doesn't change anything in the function, and from the functions called, most of them are in the `mmx` module, which wasn't changed from that commit at all. From the only ones that were changed (`_mm_setzero_ps, cvtpi2ps, _mm_movelh_ps`) nothing looks suspicious.

So at least on a first look, no idea. Its suspicous that it fails in MacOSX 32 and 64bit only, but Linux works fine. 

Maybe there was an error there (or somewhere else) already, and the code changes revealed it?

**Comment by alexcrichton** [comment]
> Maybe there was an error there (or somewhere else) already, and the code changes revealed it?

Hm yeah this seems most likely, thanks for looking! I'll keep trying to debug Travis, it's just gonna be slow as OSX is always pretty slow...

**Comment by alexcrichton** [comment]
Seems to be passing again? Dunno...
