### ISSUE TITLE
Release 0.0.3.1

### ISSUE THREAD

**Issue by AdamNiederer** [rust-lang-nursery/stdsimd#282]
Hi guys,

Would it be possible to release a version immediately before the vendor type migrations (namely at 488c28a204712823f619fefba3e3c774fdb1ad0a) to crates.io? I feel like this is a good point to cap off the "old stdsimd" before stripping away the cross-platform and lane-explicit types, which would be absent in 0.0.4. It'd also give dependent projects a good release to stay on until the crazy API revamp is complete.

**Comment by alexcrichton** [comment]
Oops sorry I meant to do this before we started the transition! I've now published 0.0.4
