### ISSUE TITLE
Implement all x86 AES-NI vendor intrinsics

### ISSUE THREAD

**Issue by ruuda** [rust-lang-nursery/stdsimd#295]
#40 makes no mention of the [AES-NI](https://en.wikipedia.org/wiki/AES_instruction_set) intrinsics, so I am opening an issue to track them here. See also the [Intel intrinsics guide](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#othertechs=AES).

  * [ ] [`_mm_aesdec_si128`](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_mm_aesdec_si128&expand=5236)
  * [ ] [`_mm_aeskeygenassist_si128`](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_mm_aeskeygenassist_si128&expand=5236)
  * [ ] [`_mm_aesenc_si128`](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_mm_aesenc_si128&expand=5236)
  * [ ] [`_mm_aesenclast_si128`](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_mm_aesenclast_si128&expand=5236)
  * [ ] [`_mm_aesimc_si128`](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_mm_aesimc_si128&expand=5236)
  * [ ] [`_mm_aesdeclast_si128`](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_mm_aesdeclast_si128&expand=5236)

**Comment by gnzlbg** [comment]
So once https://github.com/rust-lang/rust/pull/47822 is merged this can be implemented. 

In MSDN there are examples of each of these intrinsics that can be used to create some tests: https://msdn.microsoft.com/de-de/library/cc714206(v=vs.100).aspx

**Comment by ruuda** [comment]
Thanks for opening the whitelist PR @gnzlbg.

I will take a shot at implementing the intrinsics in this issue.
