### ISSUE TITLE
coresimd docs fail to build

### ISSUE THREAD

**Issue by AdamNiederer** [rust-lang-nursery/stdsimd#296]
It looks like whatever platform `cargo doc` runs as doesn't recognize some of the intrinsics used by coresimd. While we'll be removing `simd_rem`, it looks like `nontemporal_store` is also an issue in newer builds.

https://docs.rs/crate/faster/0.4.1/builds/83625

https://docs.rs/crate/coresimd/0.0.4/builds/82378

**Comment by alexcrichton** [comment]
I'm not sure there's really anything we can do about this? Maybe this issue would best be for docs.rs to update the nightly rev?

**Comment by alexcrichton** [comment]
As this crate gets more and more unstable over time we're adding it all to libstd anyway, so I think this'll fix itself in time.
