### ISSUE TITLE
Add 0.0.4 branch

### ISSUE THREAD

**Issue by AdamNiederer** [rust-lang-nursery/stdsimd#298]
0.0.4 uses the deprecated `target_feature` syntax. I've backported the fix to 0.0.4 on my fork, but I don't think I can propose a pull request to a branch which doesn't exist in the parent repository. Could we pull this branch in and publish it as a successor to 0.0.4?

https://github.com/AdamNiederer/stdsimd/tree/0.0.4

**Comment by alexcrichton** [comment]
I've just pushed up a `before-vendor-types` branch for this, want to send a PR there?
