### ISSUE TITLE
Some intrinsics aren't specified by Intel

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang-nursery/stdsimd#307]
Or at least I don't see them listed at https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=__readeflags :(

@gnzlbg did you get the names/signatures from a different source though?

**Comment by alexcrichton** [comment]
Looks like the list is:

* `__readeflags`
* `__writeflags`
* `__cpuid_count`
* `__cpuid`
* `__get_cpuid_max`

(updated the title of this issue)

**Comment by gnzlbg** [comment]
This is as intended. These intrinsics are useful and provided by all major C compilers (GCC, MSVC, Clang, ...) on all major x86 platforms as part of their intrinsics headers. 

The alternative would be to have them be part of rustc, but these intrinsics are vendor specific (should only be available on x86) and that's what `core::vendor` should be there for IIUC.

**Comment by alexcrichton** [comment]
Ok nah that makes sense! If all other compilers expose these then that seems fine for us to follow suit. I definitely think this is the right location if we're to add them!

Do you have a link handy for these definitions? I'd just like something to insert in the stdsimd-verify file for "this is why we're skipping these intrinsics"

**Comment by gnzlbg** [comment]
> Do you have a link handy for these definitions? 

Yes: 

- `__readeflags` is equivalent to GCC's `__readeflags` exposed in [`/i386/ia32intrin.h`](https://github.com/gcc-mirror/gcc/blob/master/gcc/config/i386/ia32intrin.h#L260) and Clang's `__readeflags` exposed in [`ia32intrin.h`](https://github.com/llvm-mirror/clang/blob/master/lib/Headers/ia32intrin.h#L33)
- `__writeeflags` is equivalent to GCC's `__writeeflags` exposed in [`/i386/ia32intrin.h`](https://github.com/gcc-mirror/gcc/blob/master/gcc/config/i386/ia32intrin.h#L288) and Clang's `__writeeflags` exposed in [`ia32intrin.h`](https://github.com/llvm-mirror/clang/blob/master/lib/Headers/ia32intrin.h#L52)
- `_xgetbv` is equivalent to GCC's `_xgetbv` exposed in [`i386/xsaveintrin.h`](https://github.com/gcc-mirror/gcc/blob/154452f45aad4bfe7a1f719c65cd26837f416a48/gcc/config/i386/xsaveintrin.h#L60) and Clangs' `_xgetbv` exposed in [`intrin.h`](https://github.com/llvm-mirror/clang/blob/master/lib/Headers/intrin.h#L916)
- `_cpuid_count`is equivalent to GCC's `__cpuid_count` exposed in [`i386/cpuid.h`](https://github.com/gcc-mirror/gcc/blob/master/gcc/config/i386/cpuid.h) and Clang's `__cpuid_count` exposed in [`cpuid.h`](https://github.com/llvm-mirror/clang/blob/master/lib/Headers/cpuid.h#L214)

**Comment by alexcrichton** [comment]
Ok perfect, thanks for the info @gnzlbg!
