### ISSUE TITLE
RDTSC intrinsics may not be right

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang-nursery/stdsimd#308]
After hooking them up to automatic verification there's a few inconsistencies:

* the `_rdtsc` function requires the TSC cpu feature (according to Intel) but we don't enable that (unsure if LLVM knows about it)
* ~~The `_rdtsc` function returns a 64-bit value, but that's not natively possible on 32-bit platforms~~
* The `__rdtscp` function requires the RDTSCP cpu feature according to Intel

**Comment by gnzlbg** [comment]
@shepmaster thoughts ?

**Comment by petrochenkov** [comment]
>The `_rdtsc` function returns a 64-bit value, but that's not natively possible on 32-bit platforms

Not sure about intrinsics, but `rdtsc` and `rdtscp` as instructions return their 64-bit result in two registers (`eax` and `edx`), so they can be used in 32-bit modes.

**Comment by shepmaster** [comment]
It's highly likely I didn't get the CPU feature(s) correct, so I believe that. I agree with @petrochenkov on how the 64-bit value comes about ;-)

**Comment by gnzlbg** [comment]
We can maybe make the `_rdtsc` intrinsic return a tuple of 32-bit values then? How do other compilers implement it (e.g. clang and friends) ?

**Comment by alexcrichton** [comment]
Nah I think returning a u64 is fine, it was just flagged by the verification we have because other instructions require 64-bit registers, but I think some slight translation of values here is fine.

In any case the only other remaining bits are the target features necessary here which I think is fine to have change over time (aka we retroactively can add `#[target_feature(enable = ...)]` and document how to call it. Thanks all for the info!
