### ISSUE TITLE
Implement CLMUL instruction set

### ISSUE THREAD

**Issue by newpavlov** [rust-lang-nursery/stdsimd#318]
Carry-less Multiplication (CLMUL) allows to improve the speed of applications doing block cipher encryption in Galois/Counter Mode, which depends on finite field GF(2^k) multiplication. Another application is the fast calculation of CRC values, including those used to implement the LZ77 sliding window DEFLATE algorithm in zlib and pngcrush. (wiki)

**Comment by gnzlbg** [comment]
From [`PCLMULQDQ`](http://www.felixcloutier.com/x86/PCLMULQDQ) it looks like this might lower to `vpclmulqdq` if AVX is enabled and the target os supports it, and to `vpclmulqdq` otherwise.

**Comment by newpavlov** [comment]
>Would _mm_clmulepi64_si128 be enough ?

If I understand everything correctly, yes, as other 4 instructions are equivalent to using PCLMULQDQ with `imm` equal to 0x00, 0x01, 0x10 and 0x11.

**Comment by gnzlbg** [comment]
So if somebody wants to give this a try I can mentor. It gives a pretty good overview of stdsimd and is an easy issue to solve. 

I am bad at making time estimates, but 90% of the work can be probably be done in 1-2 hours (maybe less, depending on how much Rust experience one has). The last 10% of the work involves letting the travis build bots run (they take a while) and fixing any potential issues on weirder configurations like `i586`/`i686` if any.

**Comment by newpavlov** [comment]
I've wrote a draft PRs (linked above). I've used `aes` as an example, so it does not handle AVX specific stuff.
