### ISSUE TITLE
code-gen tests should be compiled with the appropriate feature flags and platform

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang-nursery/stdsimd#33]
We need to extend the new code-gen test machinery to:

- use the features specified in the `#[target_feature = "+...,+..."]` attribute when compiling the test (or otherwise the proper assembly won't be generated and the test will fail, --release is not enough, the python script inferred this from the test name)
- specify a target platform for the tests to be compiled (e.g. the arm tests do not run on my machine anymore, the python script inferred this from the test name)

ping: @alexcrichton

**Comment by alexcrichton** [comment]
I think the first point is fixed b/c it uses the literal intrinsic as a function pointer, right? That is, the intrinsic itself surely has to have the right `#[target_feature]` annotation, so the test I think tests that literal function so should be good.

For ARM and such it's planned! If you'd like to add an couple examples in the repo I can rig up a harness to test it on Travis as well.

**Comment by gnzlbg** [comment]
> I think the first point is fixed b/c it uses the literal intrinsic as a function pointer, right? That is, the intrinsic itself surely has to have the right #[target_feature] annotation, so the test I think tests that literal function so should be good.

Indeed! I got a lot of failures on my system and thought this was not working, but the problem was that the new tests weren't querying the exact instructions that are generated. I've fixed those in #29 , `cargo test --release` should be green after that.

>  If you'd like to add an couple examples in the repo I can rig up a harness to test it on Travis as well.

I've added the tests for arm but note that `#[target_feature]` there is not used yet. I know that the right instructions are generated when:

- `arm::v6` is compiled for the target `arm-unknown-linux-gnueabihf`
- `arm::v7` is compiled for the target `armv7-unknown-linux-gnueabihf`
- `arm::v8` is compiled for the target `arch64-unknown-linux-gnu`

I've posted in the arm pull-request for help querying llc attributes for those targets. Maybe llc supports attributes for those features that can be passed via `#[target_feature]` or maybe not. I don't know.

**Comment by alexcrichton** [comment]
Thanks for fixing up OSX! I can work on implementing ARM CI today.

**Comment by gnzlbg** [comment]
I won't have much time till Saturday but I hope I can look into the
required arm features till then. Those llc dumps would help :)

**Comment by alexcrichton** [comment]
Ok I've added ARM CI in https://github.com/rust-lang-nursery/stdsimd/pull/36
