### ISSUE TITLE
cfg(target_feature) seems overly permissive

### ISSUE THREAD

**Issue by Cocalus** [rust-lang-nursery/stdsimd#350]
It's possible to use any feature name in cfg(target_feature = "anything"), which opens up the some foot guns. 

A common use for this check is for optimizing things with slower fallbacks. which means code that's supposed to run is silently replaced with a more portable fallback.

Also while  
#[target_feature(enable = "sse4.2,popcnt")] 
works 
#[cfg(all(target_arch = "x86_64", target_feature = "sse4.2,popcnt"))] 
will never be true.

If only valid identifiers could be used in the check that would avoid this, but that may break backwards compatibility. Perhaps a warning or clippy lint.

```rust
#![feature(target_feature)]
#![feature(cfg_target_feature)]
#![feature(stdsimd)]

fn main() {
    #[cfg(all(target_arch = "x86_64", target_feature = "sse4.2", target_feature = "popcnt"))]
    {
        println!("sse4.2 and popcnt enabled at build");
    }

    //that verbose let's shorten it
    #[cfg(all(target_arch = "x86_64", target_feature = "sse4.2,popcnt"))]
    {
        //This is never printed, but it seems like it should be
        //
        //In practice if there's a portable fall back, the coder may not notice
        println!("\"sse4.2,popcnt\" enabled at build");
    }

    #[cfg(all(target_arch = "x86_64", target_feature = "ssse4"))]
    {
        //It would be nice if unknown target features where a compile error to expose typos
        //but that might be bad for forward compatibility
        println!("ssse4? enabled at build");
    }
    #[cfg(all(target_arch = "x86_64", target_feature = "turbo_button"))]
    {
        println!("Why does the turbo button slow the computer down");
    }
}
```

**Comment by gnzlbg** [comment]
AFAICT this works as intended and has nothing to do with `target_feature`, this is just how `#[cfg()]` works. For example:

```rust
#[cfg(target_arch = "this_will_never_trigger")] {
   // no compilation error here
}
```

Also, `cfg` tests whether one lists contains one element, so:

```rust
#[cfg(target_arch = "x86_64,x86")] {
   // this will never trigger because the target "x86_64,x86" 
   // does not exist
}
```

One needs to write:

```rust
#[cfg(all(target_arch = "x86_64", target_arch = "x86"))] {
   // this will never trigger because no target contains
   // both x86_64 and x86
```

You can fill an issue in rust-lang/rust about this, but this is basically about changing the way `#[cfg()]` works, and is probably going to need an RFC.

**Comment by gnzlbg** [comment]
@alexcrichton I can open issues about some of the points I mentioned at the end if you want (or if @Cocalus does not beat me to it). Feel free to reopen if you disagree.

**Comment by gnzlbg** [comment]
Also @Cocalus feel free to discuss here more concrete solutions to the problems above, and ping us if you open issues upstreams or posts in internals. `stdsimd` is sadly just a normal Rust library, and there is little we can do in it about language constructs like `cfg`.
