### ISSUE TITLE
crates.io-hosted stdsimd is falling out of sync with rustc

### ISSUE THREAD

**Issue by hdevalence** [rust-lang-nursery/stdsimd#402]
Hi, using the `stdsimd` hosted on crates.io now gives warnings about `target_feature`:
```
warning: #[target_feature = ".."] is deprecated and will eventually be removed, use #[target_feature(enable = "..")] instead
   --> /home/hdevalence/.cargo/registry/src/github.com-1ecc6299db9ec823/coresimd-0.0.4/src/x86/i586/avx2.rs:247:1
```
I guess that the code in this repo has already been updated; would it be possible to publish a new `0.0.5` release to crates.io?

**Comment by BurntSushi** [comment]
Why aren't you using [`std::arch`](https://doc.rust-lang.org/nightly/std/arch/)?

From my perspective, we published `stdsimd` to crates.io to make it easy to experiment with, but now that it's in Rust proper, it's less valuable?

**Comment by hdevalence** [comment]
Ah, great, that's clearly the right answer! I stopped paying attention since last fall.
