### ISSUE TITLE
There's seemingly no way to construct a __m128i in a const fn

### ISSUE THREAD

**Issue by shepmaster** [rust-lang-nursery/stdsimd#403]
My *ideal* case would be to take a `&[u8]` and "fill up" a `__m128`:

```rust
let needle: __m128i = bytes.collect(); // Takes the first 16 bytes, zero-initialized otherwise

// or

let mut needle = __m128i::default(); // zero-initialize
needle.extend(bytes); // Takes the first 16 bytes
```

However, none of the "nice" traits are implemented for these types, and I've gotten the feeling that is no accident. Basically, I can use an intrinsic function to set it (e.g. `_mm_setzero_si128`), or I can convert from `u8x16` and friends.

The intrinsics are not `const`, so they cannot be used in a `const fn` context.

The closest I could find was

```rust
u8x16::new(
    x0, x1, x2, x3, x4, x5, x6, x7,
    x8, x9, x10, x11, x12, x13, x14, x15,
).into_bits()
```

but `into_bits` is likewise not `const`.

**Comment by BurntSushi** [comment]
I'm having trouble connecting the dots in your issue, so I'll just vomit out two things and see what sticks. :-)

> My ideal case would be to take a &[u8] and "fill up" a `__m128`:

Ignoring the "const" part of your request, I would use `_mm_loadu_si128` or `_mm_load_si128`, depending on whether you're loading unaligned or aligned data, respectively.

> There's seemingly no way to construct a `__m128i` in a const fn

I think the way to do this (right now at least) is via a union

```
union u8x16 {
    vector: __m128i,
    bytes: [u8; 16],
}

const ZERO: __m128i = unsafe { (u8x16 { bytes: [0; 16] }).vector };
```

[playground link](https://play.rust-lang.org/?gist=e2261e76a0e79608995664ed853d56a9&version=nightly)

**Comment by gnzlbg** [comment]
> I think the way to do this (right now at least) is via a union

Yes, in the future `mem::uninitialized` and `mem::zero` should become `const fn`s, which will allow you to transmute a `std::simd::u8x16` type (which has `const fn` constructors) directly into an `__,128i`. But that's blocked on https://github.com/rust-lang/rfcs/issues/411 being fixed, and on the portable packed vector types RFC being merged: https://github.com/rust-lang/rfcs/pull/2366

**Comment by shepmaster** [comment]
> `mem::uninitialized` and `mem::zero` should become `const fn`s, which will allow you to transmute a `std::simd::u8x16` type (which has `const fn` constructors) directly into an `__m128i`

I think I'm missing a step here. How do `mem::uninitialized` or `mem::zero` allow for transmuting?

**Comment by gnzlbg** [comment]
> I think I'm missing a step here. How do mem::uninitialized or mem::zero allow for transmuting?

Oh sorry, `mem::transmute` is what should become `const fn` here.

**Comment by alexcrichton** [comment]
I think this has basically been resolved, so closing
