### ISSUE TITLE
Just me or is `impl From<_> for u8x16` missing?

### ISSUE THREAD

**Issue by TheIronBorn** [rust-lang-nursery/stdsimd#420]
There are impls for all `u8x_::from` except `u8x16`.

**Comment by TheIronBorn** [comment]
I'm using merely `#![feature(stdsimd)]`.

But I'm looking to cast each lane of a u16x16 to u8.  For other vectors this seems to be `from` and not `from_bits`.  Am I mistaken in thinking I don't want `from_bits`?

**Comment by gnzlbg** [comment]
> I'm looking to cast each lane of a u16x16 to u8.

Then you need `impl From<u16x16> for u8x16` and you are right, all `u8x16` and all `i8x16` impls are missing.

**Comment by gnzlbg** [comment]
https://github.com/rust-lang-nursery/stdsimd/pull/421 should fix this.

**Comment by gnzlbg** [comment]
Closed by #421 .
