### ISSUE TITLE
PartialOrd should evaluate all lanes

### ISSUE THREAD

**Issue by TheIronBorn** [rust-lang-nursery/stdsimd#433]
I expected code like `x < y` to test all lanes but this seems to only evaluate the first.
```rust
let foo = u32x2::new(0, 100) < u32x2::new(100, 0);
assert_eq!(foo, false); // fails
```
([playground link](https://play.rust-lang.org/?gist=c2487d75c81294b42d4f9118089eeab6&version=nightly&mode=debug))

Is this the expected behavior?  If so I think that ought to be in the docs.

**Comment by TheIronBorn** [comment]
I believe it's due to `#[derive(PartialOrd)]`.
This does the same ([playground](https://play.rust-lang.org/?gist=2220de0e55bf8fe96df1c5a67f149817&version=nightly&mode=debug)):
```rust
#[derive(PartialEq, PartialOrd)]
struct Foo(u8, u8);

let foo = Foo(0, 100) < Foo(100, 0);
assert_eq!(foo, false);

**Comment by gnzlbg** [comment]
> Is this the expected behavior? 

`PartialOrd` compares vectors lexicographically, that is, `u32x4(0,1,3,4) > u32x4(0,1,2,100)`. Per the RFC, this is the intended behavior. If you disagree, chime in the discussion there: https://github.com/rust-lang/rfcs/pull/2366

> If so I think that ought to be in the docs.

The behavior is not set in stone yet and changes as the RFC is updates. Until the RFC is merged, consider the RFC to be the docs. Feel free to send PRs updating the docs to the status of the RFC though.

**Comment by TheIronBorn** [comment]
Thanks!
