### ISSUE TITLE
apparent typo in macro for aarch64

### ISSUE THREAD

**Issue by ExpHP** [rust-lang-nursery/stdsimd#442]
so I don't know the first goddamn thing about ARM, but there's just something about this that don't look right:

https://github.com/rust-lang-nursery/stdsimd/blob/2f86c75a2479cf051b92fc98273daaf7f151e7a1/stdsimd/arch/detect/arch/aarch64.rs#L51-L54

**Comment by alexcrichton** [comment]
Ah good catch, looks like a typo!
