### ISSUE TITLE
macros should support trailing commas

### ISSUE THREAD

**Issue by ExpHP** [rust-lang-nursery/stdsimd#443]
Since the macros from this crate are now showing up as reexported from std, I'm going to be taking it upon myself to make sure that they all support trailing commas.

(you know, the one trailing comma that nobody will ever care about or want to take advantage of because the only argument is a literal string of finite length)

**Comment by ExpHP** [comment]
I, uh... oops.

IIRC, I started to do this, but then shuddered at the thought of how I would add test cases to [this file](https://github.com/rust-lang/rust/blob/ddab91a5debadfda47c057117c8b498a31abaae7/src/test/run-pass/macro-comma-support.rs). (or anywhere else for that matter). And then shortly thereafter I forgot.

**Comment by gnzlbg** [comment]
currently we only re-export the `is_{arch}_feature_detected!` macros, so maybe just create a file in `crates/stdsimd/tests/macro_trailing_commas.rs` and adds tests for these of the form:

```rust
let _ = is_x86_feature_detected!("sse"); 
let _ = is_x86_feature_detected!("sse", ); 
```
