### ISSUE TITLE
need to upgrade proc_macro

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang-nursery/stdsimd#454]
cc @alexcrichton 

CI started failing yesterday: https://ci.appveyor.com/project/rust-lang-libs/stdsimd/build/1.0.1243#L114

**Comment by alexcrichton** [comment]
Yeah this is waiting on https://github.com/dtolnay/syn/pull/426 now

**Comment by lu-zero** [comment]
It got merged and https://github.com/rust-lang-nursery/stdsimd/pull/455 makes the CI a bit greener :)

**Comment by alexcrichton** [comment]
Should now be done!
