### ISSUE TITLE
Disasm demangling mismatch on windows

### ISSUE THREAD

**Issue by lu-zero** [rust-lang-nursery/stdsimd#456]
Looks like we have another issue with the disassembler and the demangler

https://ci.appveyor.com/project/rust-lang-libs/stdsimd/build/1.0.1255

Should we seriously consider using https://github.com/m4b/goblin to try to have more control?

**Comment by alexcrichton** [comment]
Let's find the actual bug first and go from there.

**Comment by lu-zero** [comment]
It is quite similar to the issue I had on ppc64 on linux before I updated the rustc_demangle version.

```
coresimd::x86_64::sse2::assert__mm_cvttsd_si64_cvttsd2si stdout ----
maybe related functions
	- coresimd::coresimd::x86_64::sse2::assert__mm_cvttsd_si64_cvttsd2si::_mm_cvttsd_si64_shim
```

backtrace and the local disassembler seem to output slightly different symbols and they get demangled to different strings.

**Comment by alexcrichton** [comment]
I think the previous errors may be a red herring? All green now -- https://ci.appveyor.com/project/rust-lang-libs/stdsimd/build/1.0.1261

**Comment by lu-zero** [comment]
I hate when something works (or breaks) without apparent reason. I do not use windows so I cannot investigate. Shall we close this issue and hope to not have to reopen it? :)

**Comment by alexcrichton** [comment]
Sure yeah, sounds good
