### ISSUE TITLE
Add more `PartialEq` portable vector tests

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang-nursery/stdsimd#457]
Currently we only test `PartialEq` for vectors whose elements have all the same value. We should have some mixed tests as well.

**Comment by gnzlbg** [comment]
cc @lu-zero this might help with diagnosing the ppc and ppc64 issues

**Comment by lu-zero** [comment]
The ppc/ppc64 issues depend on https://github.com/rust-lang/rust/issues/50960 first I'm afraid.

**Comment by gnzlbg** [comment]
Fixed in https://github.com/rust-lang-nursery/stdsimd/commit/4751cb9ca1f01467e91d0fdfb9cba8a9d30d3bdb
