### ISSUE TITLE
Expose is_x86_feature_detected to libcore

### ISSUE THREAD

**Issue by g2p** [rust-lang-nursery/stdsimd#464]
(not sure if this is the correct issue tracker)

This would be useful for Nebulet, which compiles as no_std.

**Comment by gnzlbg** [comment]
This is the correct issue tracker. Since `is_x86_feature_detected` requires operating-system support it cannot be provided in `libcore`.

`core::arch` provides you with the pieces required to build a run-time feature detection systems, so you could use that to build one that Nebulet can use, for example, based on the one provided by `std`.

You could provide it as an independent crate, so that others can use it, but just keep in mind that `#[no_std]` crates do not necessarily run on ring 0, nor on Nebulet, and that run-time feature detection in other system might require a different implementation.

**Comment by g2p** [comment]
I did not realize the feature needed extra support, thank you for the informative reply.
At the moment I'm using https://github.com/gz/rust-cpuid to check for features in a no_std context.

**Comment by gnzlbg** [comment]
Appears to be similar to [`cupid`](https://github.com/shepmaster/cupid) in that it maps directly to the `cpuid` instruction. 

Just keep in mind that a `cpuid` bit being set does not always imply that a feature can be used correctly (that is, without invoking undefined behavior). For some features like some of the SIMD related ones whether a feature can be used correctly will also depend on whether OS support is required, and if that's the case, on whether it is properly enabled.

**Comment by RReverser** [comment]
I'm currently using code like

```rs
if cfg!(feature = "use_std") {
  is_x86_feature_detected!("sse4.2")
} else {
  cfg!(target_feature = "sse4.2")
}
```

to work around this. I wonder if it would make sense for `core` to provide a fallback version of `is_x86_feature_detected!` that would do at least the second part (transparently falling back to at least compile-time target feature flag).

**Comment by gnzlbg** [comment]
>  I wonder if it would make sense for core to provide a fallback version of is_x86_feature_detected! that would do at least the second part (transparently falling back to at least compile-time target feature flag).

We actually want to be able to use full run-time feature detection from `core` (including being able to use the `libstd` system from core if `libstd` ends up linked in the final binary), but it is unclear right now how to do it. RFC2492 might be what we need, I've left a comment about this there yesterday (https://github.com/rust-lang/rfcs/pull/2492#issuecomment-422783212 ).

**Comment by gnzlbg** [comment]
@RReverser in the mean time, if you end up doing that a lot, it would make sense to just write your own macro to abstract it away.

**Comment by josephlr** [comment]
> Since `is_x86_feature_detected` requires operating-system support it cannot be provided in `libcore`.

@gnzlbg I'm a bit confused by this. For x86, all features are detected via CPUID or via XCR0 (which requires the OS to enable osxsave), both of which are available in usersapce. This means that while OS support is needed to _enable_ these features, no OS support is needed to _detect_ these features. The [`detect_features` function](https://github.com/rust-lang/stdarch/blob/f1934fdf58c346dcd676eac4f70f5434ba09baba/crates/std_detect/src/detect/os/x86.rs#L28) doesn't use anything that's not already in `libcore`. `std_detect` even notes that "On x86/x86_64 no OS specific functionality is required": https://github.com/rust-lang/stdarch/blob/f1934fdf58c346dcd676eac4f70f5434ba09baba/crates/std_detect/src/detect/mod.rs#L97

Both ring (see the linked issue) and getrandom (for the [RDRAND implementation](https://github.com/rust-random/getrandom/blob/11b4f9e406ce4a8f9c5a4b540e65c65f3231ff8b/src/rdrand.rs#L67-L69)) have had to work around this by duplicating parts of `std_detect`'s code in their own crates. This seems unnecessary.
 
 I know the story for other arches is different, but it seems like nothing is preventing providing `is_x86_feature_detected!()` as part of libcore.
