### ISSUE TITLE
Add _MM_SHUFFLE macro for x86/x86_64

### ISSUE THREAD

**Issue by bitshifter** [rust-lang-nursery/stdsimd#475]
`xmmintrin.h` defines a _MM_SHUFFLE macro which is use to generate the mask used for `_mm_shuffle` and other similar instructions. https://clang.llvm.org/doxygen/xmmintrin_8h.html#a65a052b655bd49ff3fe128b61847df9f. I could not find this macro in `std::arch::x86`, perhaps it is there but doesn't show up in the docs?

In any case, if it's missing perhaps it would be good to add it. Creating masks by hand is cryptic and having an equivalent to `_MM_SHUFFLE` would make using the Rust intrinsics more like other languages.

**Comment by gnzlbg** [comment]
Thanks for reporting this. Wanna send a PR? Should be pretty easy to implement (check the other macros and `const`s in the `coresimd/x86/sse.rs` module.

**Comment by bitshifter** [comment]
Will do.

**Comment by bitshifter** [comment]
@gnzlbg it turns out this is not so straight forward. I've added the macro and a test in this commit https://github.com/bitshifter/stdsimd/commit/727bc111c80f70ef103e0e1d93ad9cf37824a08a however it seems that coresimd is re-exported via stdsimd, but I do not know how to re-export the macro.

I was reminded about binary literals when looking at the tests, which are reasonably readable. Perhaps if this macro issue is not easily solved adding and boolean literal example would help.

**Comment by gnzlbg** [comment]
@bitshifter you should add a `const fn` instead of a macro, or why does it need to be a macro?

**Comment by gnzlbg** [comment]
Also, you should call it `_MM_SHUFFLE` and not `_mm_shuffle`.
