### ISSUE TITLE
The doc-test for __m256 is wrongly guarded by `#[target_feature(enable = "sse")]`

### ISSUE THREAD

**Issue by kennytm** [rust-lang-nursery/stdsimd#481]
... it should be `"avx"`.

https://github.com/rust-lang-nursery/stdsimd/blob/5d300a55cf521a035f40c1ef9869ed277c055312/coresimd/x86/mod.rs#L278-L286

See rust-lang/rust#51675 for detail.

**Comment by mnd** [comment]
@gnzlbg Is line ` /// # if is_x86_feature_detected!("sse") { unsafe { foo() } } ` should be changed too?

**Comment by gnzlbg** [comment]
@mnd it was changed in the next commit: https://github.com/rust-lang-nursery/stdsimd/commit/66267294183beef1349d107443fd4c0103a227ac
