### ISSUE TITLE
Cannot compile coresimd with cargo

### ISSUE THREAD

**Issue by rococtz** [rust-lang-nursery/stdsimd#488]
Hi,

I have just tried added `stdsimd` to my `Cargo.toml` dependencies:
```
[dependencies]
stdsimd = "*"

```
and perform `cargo run` but it fails with hundreds of erros:
```
60 | #[target_feature = "+xsave,+xsaveopt"]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: #[target_feature] attribute must be of the form #[target_feature(..)]
  --> C:\Users\office\.cargo\registry\src\github.com-1ecc6299db9ec823\coresimd-0.0.4\src\x86\x86_64\xsave.rs:73:1
   |
73 | #[target_feature = "+xsave,+xsavec"]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: #[target_feature] attribute must be of the form #[target_feature(..)]
  --> C:\Users\office\.cargo\registry\src\github.com-1ecc6299db9ec823\coresimd-0.0.4\src\x86\x86_64\xsave.rs:87:1
   |
87 | #[target_feature = "+xsave,+xsaves"]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: #[target_feature] attribute must be of the form #[target_feature(..)]
   --> C:\Users\office\.cargo\registry\src\github.com-1ecc6299db9ec823\coresimd-0.0.4\src\x86\x86_64\xsave.rs:103:1
    |
103 | #[target_feature = "+xsave,+xsaves"]
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 973 previous errors

error: Could not compile `coresimd`.

To learn more, run the command again with --verbose.

```
My current versions:
```
rustup 1.11.0 (e751ff9f8 2018-02-13)
rustc 1.28.0-nightly (cbc4c8380 2018-06-22)
cargo 1.28.0-nightly (e2348c2db 2018-06-07)
Windows 10 (with Command Prompt)
```

**Comment by gnzlbg** [comment]
looks like for some reason these weren't updated

**Comment by BurntSushi** [comment]
This isn't trying to compile master. This is trying to compile stdsimd from crates.io.

What problem are you trying to solve? You generally shouldn't be using this crate directly.

**Comment by gnzlbg** [comment]
You have to use the master branch from git. The correct thing to do to use stdsimd directly is:

```toml
[dependencies]
stdsimd = { git = "https://github.com/rust-lang-nursery/stdsimd.git" }
```

Need to add this to the README.md

**Comment by rococtz** [comment]
What I am actually trying to do is to install [rustface](https://github.com/atomashpolskiy/rustface) from crates.io which fails because `stdsimd` fails to compile. I have raised this [issue ](https://github.com/atomashpolskiy/rustface/issues/7)with them. 

To quote the guys from `rustface`:

> Seems to me like current simd version is outdated and incompatible with current Rust version

**Comment by BurntSushi** [comment]
I see. rustface needs to stop using stdsimd on crates.io.
