### ISSUE TITLE
Deprecate `stdsimd` from crates.io

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang-nursery/stdsimd#491]
We should do a `0.0.5` release of `coresimd` and `stdsimd` on crates io that contains an empty lib, and a README explaining that using `stdsimd` via crates.io is deprecated with instructions about how to migrate to `std/core`.

Those who want to use the master branch should do that directly on their `Cargo.toml`.

**Comment by gnzlbg** [comment]
@alexcrichton I think we should do another release (0.0.6) of the crates here on crates.io, and continue do so until one can properly and easily recompile std with different target features enabled. Otherwise one won't be really able to use e.g. neon on armv7, simd128, etc.

**Comment by alexcrichton** [comment]
Seems reasonable to me, although I would prefer to not personally be on the hook for updating crates.io whenever we make a breaking change to the compiler. If you'd like to though I have no problem having these crates on crates.io!

**Comment by gnzlbg** [comment]
I'll be on the hook for updating it. I've published a branch, and updated the "middle" version, since std::simd was removed, and maybe some people are somehow still using 0.0.5. The branch is https://github.com/rust-lang-nursery/stdsimd/tree/stdsimd_0_1_0_publish
