### ISSUE TITLE
Optimize has_cpuid for x86 targets with know support

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang-nursery/stdsimd#497]
For example, we could check if the `x86` target has `mmx` support and return `true` unconditionally if that's the case.

**Comment by stevecheckoway** [comment]
I'm not sure mmx is the correct feature to check for. One can compile for, for example,
``` json
{
  "llvm-target": "i686-unknown-none",
  "features": "-mmx"
  ...
}
```

But it's presence is certainly sufficient.

If I'm reading [this](https://github.com/rust-lang/rust/blob/256e497fe63bf4b13f7c0b58fa17360ca849c54d/src/librustc_back/target/mod.rs#L293) correctly (and I'm just poking around for the first time now), there are a whole bunch of features that are available. I'm not sure which features are exposed, but perhaps one could check for the presence of at least one of a set of them that imply `cpuid` support.

**Comment by gnzlbg** [comment]
So i've just sent a PR that just tests for SSE and returns true if that's enabled at compile-time. Should just work for all i586 rust targets and upwards, but for non Rust targets we can probably do better. 

I am leaving this open and changing difficulty to medium because PRs that improve on this are welcomed.

**Comment by gnzlbg** [comment]
I'm closing this, improving this further is not worth tracking IMO, but if somebody sends PR I'll accept them.
