### ISSUE TITLE
Shall we split the `std::simd` module into a crate separate from std?

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang-nursery/stdsimd#525]
I have a pretty much equivalent implementation of `stdsimd` that follows the RFC in https://github.com/gnzlbg/ppv

Given that:

* the stabilization path for `std::simd` is not clear yet, and that stabilization might take a while
* there are issues with some targets failing with `core` upstream, e.g., due to linkage issues
* `std::simd` costs most of the CI time of the `stdsimd` repo, 

I'd like to discuss whether we should split `std::simd` into a crate separate from `std` (not necessarily mine, we can put the current implementation 1:1 as is in the nursery).

Splitting the crate might let us sync upstream more often and without breakage with `stdsimd`, significantly reducing the amount of churn we are seeing.

cc @alexcrichton 

---

This basically turns `rust-lang-nursery/stdsimd` into `stdarch`, and the current `std::simd` into a crates on crates.io that people can just use with nightly in an opt-in way.

**Comment by alexcrichton** [comment]
Seems reasonable to me!

**Comment by hdevalence** [comment]
Hi, I was using `core::simd`. Would it be possible to not remove it until the replacement is available on crates.io?
