### ISSUE TITLE
Please revert #528 until a replacement for `core::simd` is actually available.

### ISSUE THREAD

**Issue by hdevalence** [rust-lang-nursery/stdsimd#539]
The `core::simd` module was recently deleted (#525) in favour of a future SIMD crate.  However, this crate is not available for use, meaning that there is no possible migration for code that was using `core::simd`.

I understand that nightly features are unstable and subject to change, and that code using nightly features will need to evolve as those features do, but deleting the entire `core::simd` module in favour of a not-yet-existing alternative seems like unnecessary breakage, especially because there's no path forward for code that was using it.

Couldn't removing `core::simd` wait until *after* the replacement is ready for use?

**Comment by gnzlbg** [comment]
> However, this crate is not available for use,

https://github.com/rust-lang-nursery/packed_simd

**Comment by hdevalence** [comment]
Yes, but that crate is only available as a git repository, so it cannot actually be used by any other crate on crates.io, which rejects uploads that specify git dependencies.

**Comment by gnzlbg** [comment]
> Yes, but that crate is only available as a git repository, so it cannot actually be used by any other crate on crates.io, which rejects uploads that specify git dependencies. 

Yes, but all crates on crates.io that were using `core::simd` are now broken because of this, so in some sense, it is a feature. 

Anyways, the crate is publication ready modulo docs, I can do a 0.1 release on crates.io any time if this is needed, even if the docs aren't complete.

**Comment by alexcrichton** [comment]
@gnzlbg could `packed_simd` perhaps have publishes on crates.io for ease of use? It's in general much easier to use deps from crates.io, and although old implementations break over time that's sort of expected with nightly-only crates.

**Comment by gnzlbg** [comment]
The main blocker was that it has a git dependency on `coresimd` for some targets. I fixed that by making that an optional dependency, but I haven't experimented which what happens when other crates.io target try to unconditionally enable that feature. 

I'll do a release today, but without the git dependency on `coresimd` YMMV significantly depending on target.

**Comment by gnzlbg** [comment]
@alexcrichton what happens if @hdevalence enables a `packed_simd` feature unconditionally that requires a git dependency? Will @hdevalence be able to publish to crates.io without having to make that feature optional?

**Comment by gnzlbg** [comment]
So I tried to publish it today, but the optional dependency on coresimd was preventing that (good news I guess, i don't know why I thought that was possible, maybe cargo publish dry run allows it?).

There is a published version on crates.io without the coresimd feature: https://crates.io/crates/packed_simd

Which has its own branch in the packed_simd repo: https://github.com/rust-lang-nursery/packed_simd/tree/release_0_0_1

I strongly encourage using the master branch via `git = ...` in the `Cargo.toml`.

If for whatever reasons things break, or there are improvements in `master` that you want to use, please fill an issue in the packed_simd repo, and I'll branch master again, apply the same workaround, and publish a new release.
