### ISSUE TITLE
Delete the old wasm memory intrinsics

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang-nursery/stdsimd#563]
They've changed official names in the standard and we tweaked their interface in https://github.com/rust-lang-nursery/stdsimd/pull/560, let's delete them once that change has propagated enough!

**Comment by tlively** [comment]
FYI one final instruction name bikeshed is coming through the works. https://github.com/WebAssembly/spec/issues/884

**Comment by alexcrichton** [comment]
Done now!
