### ISSUE TITLE
Are the `setr` intrinsics correct?

### ISSUE THREAD

**Issue by hdevalence** [rust-lang-nursery/stdsimd#566]
The Intel intrinsics documentation says that the `setr` intrinsics (e.g., `_mm256_setr_epi32`) are supposed to set their arguments in reverse order, so that for instance `_mm256_setr_epi32` places `e7` in the first lane of the vector:  https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=setr&expand=5236,33,4698,3266,4697

But the definition in stdsimd is
```rust
pub unsafe fn _mm256_setr_epi32(
    e0: i32, e1: i32, e2: i32, e3: i32, e4: i32, e5: i32, e6: i32, e7: i32,
) -> __m256i {
    mem::transmute(i32x8::new(e0, e1, e2, e3, e4, e5, e6, e7))
}
```

Does `i32x8::new` reverse the order of its arguments? If not, isn't this going to end up with a reversed order compared to the specification?

**Comment by hdevalence** [comment]
Should I make a PR to fix this? Is that possible wrt stability (I mean, is this considered a bug, or now that the incorrect behaviour was stabilized, is it unfixable?)

**Comment by gnzlbg** [comment]
What do the other `_setr` intrinsics do, are they correct? (IIRC some of the other ones do set the values in reverse order). Also, the `i32x4` types are not stable, so I don't know how big of a deal it would be. I guess code that uses `setr` to set the values, and then shuffles or unpacks to extract them will be able to observe that we reverse the order here. 

I think this is a bug that we should and can fix (stability allows fixing bugs). cc @alexcrichton

**Comment by alexcrichton** [comment]
While surprising [these two programs](https://gist.github.com/alexcrichton/531dc598eb5077a9aaafcdc3f529a0ea) have the same output, so I don't think that there's a bug here?

**Comment by gnzlbg** [comment]
Both clang and GCC produce the same output for me as for you, but AFAIK from the docs the output (when using `u16`) should be `[7, 6, 5, 4, 3, 2, 1, 0]` (elements initialized in reverse order).

**Comment by gnzlbg** [comment]
@hdevalence this is not a bug, if you look at the intrinsics guide, it gives this signature:

```c++
__m128i _mm_setr_epi16 (short e7, short e6, short e5, short e4, short e3, short e2, short e1, short e0)
```

and specifies the following semantics

```
dst[15:0] := e7
dst[31:16] := e6
dst[47:32] := e5
dst[63:48] := e4
dst[79:64] := e3
dst[95:80] := e2
dst[111:96] := e1
dst[127:112] := e0
```

The first argument is `e7` and its but in the bits `[15:0]` which is exactly what's happening here.

**Comment by gnzlbg** [comment]
In other words, this intrinsic initializes the elements of the vector in reverse order, but the order of the arguments is also reversed, so that it initializes the vector in the order of the arguments that one provides. Damn.
