### ISSUE TITLE
AVX stream intrinsics signatures are incorrect, maybe unsound

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang-nursery/stdsimd#575]
In the intel intrinsics guide, the signature is:

```c
void _mm256_stream_si256 (__m256i * mem_addr, __m256i a)
```

but in Rust the signature is:

```rust
pub unsafe fn _mm256_stream_si256(mem_addr: *const __m256i, a: __m256i)
```

Note that the `mem_addr` pointer is `const` in Rust, but not in C. Since the only purpose of this function is to write through this pointer, it is probably unsound for it to take a `const` pointer.

EDIT: `_mm256_stream_pd` and `_mm256_stream_ps`  also have this same issue. The SSE ` _mm_stream_ps`, `_mm_stream_pd`, and ` _mm_stream_pi` intrinsics correctly use `*mut` here.

A tangential bug is that the intrinsic verification failed hard here, since the C intrinsics do not use `const` pointers, it would have been safer to require these intrinsics to use `mut` pointers.

**Comment by alexcrichton** [comment]
Oh dear sounds bad! It may be the case though we can fix this without practical breakage. Want to send a PR and we can crater?

**Comment by gnzlbg** [comment]
Will do.

**Comment by RalfJung** [comment]
Notice that `*const T` and `*mut T` are equivalent in terms of UB, so this is not -- on its own -- unsound.

However, it could lead to people using `&T` on the call site, and that would be unsound.

**Comment by gnzlbg** [comment]
Yes, we should just have had a single pointer type :/
