### ISSUE TITLE
_mm_min_epu16 yields a call instruction

### ISSUE THREAD

**Issue by brian-armstrong** [rust-lang-nursery/stdsimd#583]
The _mm_min_epu16 intrinsic yields a call instruction to a new address. The reason for this is unclear to me, but I see it both in "real" code and in godbolt

https://gcc.godbolt.org/z/ZbWsDk

Real code:
```
_mm_min_epu16:
+0x00	pushq               %rbp
+0x01	movq                %rsp, %rbp
+0x04	pminuw              %xmm1, %xmm0
+0x09	movdqa              %xmm0, (%rdi)
+0x0d	popq                %rbp
+0x0e	retq

Other code:
...
+0x1040	        leaq                -96(%rbp), %rdi
+0x1044	        movaps              -112(%rbp), %xmm0
+0x1048	        movaps              -192(%rbp), %xmm1
+0x104f	        callq               _mm_min_epu16
```

It's unclear to me why this wouldn't simply emit `pminuw`. This sequence of instructions is unfortunate since min instructions are useful for eliding branching conditionals, but the call sequence is also fairly expensive.

**Comment by BurntSushi** [comment]
I don't see any compilation flags or runtime `target_feature` directives that enable sse4.1, which `_mm_min_epu16` requires. So what you're seeing looks expected to me. You'll want to give the [CPU feature detection docs](https://doc.rust-lang.org/std/arch/index.html#cpu-feature-detection) a careful read.

**Comment by gnzlbg** [comment]
@brian-armstrong please feel free to ask any follow up questions here. As @BurntSushi mentions that example is working as intended because it is calling an `sse4.1` function from a function that does not have the `sse4.1` feature enabled (`main` in this case).

**Comment by brian-armstrong** [comment]
Ah, that's embarrassing. Thanks for catching that.
