### ISSUE TITLE
_mm256_mpsadbw_epu8 cannot be selected by LLVM

### ISSUE THREAD

**Issue by BurntSushi** [rust-lang-nursery/stdsimd#59]
Specifically:

https://github.com/rust-lang-nursery/stdsimd/blob/9d3e1d2c0e04a5af08342e1ff177648e262bbd46/src/x86/avx2.rs#L472-L488

The error message is

```
LLVM ERROR: Cannot select: intrinsic %llvm.x86.avx2.mpsadbw
```

It's not clear how to debug these sorts of things. As far as I can tell, the extern declaration 

https://github.com/rust-lang-nursery/stdsimd/blob/9d3e1d2c0e04a5af08342e1ff177648e262bbd46/src/x86/avx2.rs#L1054-L1055

matches the [LLVM declaration](https://github.com/llvm-mirror/llvm/blob/f3898aeacac28bed38f345e29c125ac2adbd08cb/include/llvm/IR/IntrinsicsX86.td#L2165)

```
  def int_x86_avx2_mpsadbw : GCCBuiltin<"__builtin_ia32_mpsadbw256">,
              Intrinsic<[llvm_v16i16_ty], [llvm_v32i8_ty, llvm_v32i8_ty,
                         llvm_i8_ty], [IntrNoMem, Commutative]>;
```

**Comment by alexcrichton** [comment]
Doesn't imm8 need the constify treatment?

**Comment by BurntSushi** [comment]
omg, derp, yes
