### ISSUE TITLE
ssse3 `_mm_abs_pi8` : Intrinsic has incorrect return type!

### ISSUE THREAD

**Issue by gwenn** [rust-lang-nursery/stdsimd#74]
Try [fn _mm_abs_pi8(a: i8x8) -> u8x8](https://gist.github.com/gwenn/01d84c1a7c7d7b33fa996a51949e342f) patch or [fn _mm_abs_pi8(a: i8x8) -> i8x8](https://gist.github.com/gwenn/7a37f3146bee665a9ebb9523bee25793) to reproduce the error:
```
Intrinsic has incorrect return type!
<8 x i8> (<8 x i8>)* @llvm.x86.ssse3.pabs.b
LLVM ERROR: Broken function found, compilation aborted!
error: Could not compile `stdsimd`.
```

**Comment by BurntSushi** [comment]
For context, LLVM seems to think this should return an MMX type, and I've had problems getting other intrinsics with similar types to work with Rust as well. I don't quite know how to debug it though.

**Comment by alexcrichton** [comment]
According to the [LLVM test](https://github.com/llvm-mirror/llvm/blob/28d0dba22b66c461703c9129779f2956c37f14b5/test/CodeGen/X86/mmx-intrinsics.ll#L1236) for this there's a dedicated [`x86_mmx` type](http://llvm.org/docs/LangRef.html#x86-mmx-type) for this which we're not currently using. I think this'll require compiler changes to use `x86_mmx` for sure?

**Comment by gwenn** [comment]
@alexcrichton You mean rustc changes ? And then we can cast `i8x8` to `x86_mmx` ?

**Comment by alexcrichton** [comment]
I think the `i8x8` type needs to be defined as `x86_mmx` on x86 targets similarly to how `i16x8` is defined as `<i16 x 8>` as a type. Not sure why these are different at the LLVM layer, but something we'll have to take care of in rustc for sure.

**Comment by alexcrichton** [comment]
I've opened up an [upstream PR](https://github.com/rust-lang/rust/pull/45367) to add this type

**Comment by alexcrichton** [comment]
Ok! Took awhile but the upstream support is now landed and should be available for us to integrate with :)

**Comment by gwenn** [comment]
@alexcrichton Sorry, but still the same error on my [side](https://github.com/gwenn/stdsimd/commit/cc0191cec8f1e83353807ced20c52c721f2712e2)
> rustc 1.23.0-nightly (e97ba8328 2017-11-25)

**Comment by MaloJaffre** [comment]
I think this landed in master, but not yet in nightly.

**Comment by gwenn** [comment]
@MaloJaffre Thanks, I will try tomorrow.

**Comment by alexcrichton** [comment]
@gwenn the types will need to look like:

```rust
#[simd]
struct i8x8(i64);
```

**Comment by gwenn** [comment]
@alexcrichton Ok, it works.
But it seems that I am not the only one working on this: https://github.com/gnzlbg/stdsimd/tree/intr2
Maybe I should wait until the `intr2` is merged ?
And @gnzlbg created/moved the `x86_mmx`/`_m64` type  in the i686 module.
Should ssse3 also be moved in i686  ?
Thanks.
