### ISSUE TITLE
sse4.2: string comparison functions lacking good documentation

### ISSUE THREAD

**Issue by dlrobertson** [rust-lang-nursery/stdsimd#76]
The sse4.2 string comparison intrinsics are useful but very complex. Most (if not all) would benefit from examples and a descriptions of the effects the various modes have on the function.

See: https://github.com/rust-lang-nursery/stdsimd/pull/70#pullrequestreview-66118291

**Comment by dlrobertson** [comment]
Mostly just to make sure I don't forget to circle back and do this once I get sse4.2 covered

**Comment by dlrobertson** [comment]
Worked on this some last night. Should have a WIP PR in shortly to get some early feedback

**Comment by alexcrichton** [comment]
Fixed in https://github.com/rust-lang-nursery/stdsimd/pull/94! (although please let me know if I'm wrong)

**Comment by dlrobertson** [comment]
Yeah, I'm good with closing it here. I might circle back to document some of the other functions later.
