### ISSUE TITLE
Feature::power8 seems wrong

### ISSUE THREAD

**Issue by MikaelUrankar** [rust-lang-nursery/stdsimd#760]
In crates/std_detect/src/detect/os/linux/powerpc.rs, Feature::power8 is checked with auxv.hwcap but according to https://github.com/torvalds/linux/blob/master/arch/powerpc/include/uapi/asm/cputable.h#L39-L40 it should be auxv.hwcap2

**Comment by lu-zero** [comment]
You are right, do you have a patch to address it handy?
