### ISSUE TITLE
Question: Naming of C macros

### ISSUE THREAD

**Issue by nominolo** [rust-lang-nursery/stdsimd#84]
I think for convenience we also want to implement not just the core intrinsics but also convenience macros. For example, there are a number of [convenience macros][1] around the  `_mm_getcsr` intrinsic. For the following macro:

```c
#define _MM_GET_EXCEPTION_MASK() (_mm_getcsr() & _MM_MASK_MASK)
```

In Rust, we would define the same thing as a function:

```rust
#[inline(always)]
#[target_feature = "+sse"]
pub unsafe fn _MM_GET_EXCEPTION_MASK() -> u32 {
    _mm_getcsr() & _MM_MASK_MASK;
}
```
But in Rust we normally wouldn't use all-uppercase for a function name. So, the question here is: Should we
 * use C naming convention for familiarity/compatibility with the C API, or
 * use Rust naming convention for Rust-internal consistency?

Personally, I'm leaning towards the second option (i.e., lower-case), because most search tools are case-insensitive, so anyone who knows the name will be able to find it.

[1]: https://github.com/llvm-mirror/clang/blob/05083095a0a8730ad27117ef1f516f47be9bdf2c/lib/Headers/xmmintrin.h#L2922

**Comment by alexcrichton** [comment]
I might lean a bit towards the C naming convention, as basically everything in this crate is intended to follow the same conventions as C as opposed to following Rust conventions. If we were following Rust conventions we'd probably be using the module system and avoiding weird names :)

**Comment by alexcrichton** [comment]
In #88 ended up landing the upper case names, so closing!
