### ISSUE TITLE
development strategy for support beyond host platform

### ISSUE THREAD

**Issue by BurntSushi** [rust-lang-nursery/stdsimd#92]
I would like it to be possible for programmers to run tests using intrinsics that their development platform doesn't have access to. For example, as someone developing on an Intel SandyBridge machine, I'd like to be able to run tests that use AVX512 intrinsics or even ARM tests.

Is this possible? Can some kind of VM make this happen?

[@mattico noted some thoughts on the topic](https://github.com/rust-lang-nursery/stdsimd/issues/13#issuecomment-330424539).

**Comment by AdamNiederer** [comment]
AFAIK QEMU doesn't support emulating AVX-512 on processors which don't support it, but Intel has a proprietary (I know, eww) solution to do it: https://software.intel.com/en-us/articles/intel-software-development-emulator/

I'll report on whether it can handle NEON as soon as my aarch64 toolchain builds.

**Comment by alexcrichton** [comment]
Bah I would have hoped we could just use QEMU for this, but apparently not :(

**Comment by gnzlbg** [comment]
@AdamNiederer 

> AFAIK QEMU can't emulate AVX-512 in software,

Does anybody know if this is going to stay this way, or if it is something being worked on?

**Comment by Rtoax** [comment]
Thanks, qemu tcg 8.2.2 still not support avx512 yet:

```
$ qemu-x86_64 -cpu Skylake-Server ./vfmadd231ps
qemu-x86_64: warning: TCG doesn't support requested feature: CPUID.07H:EBX.hle [bit 4]
qemu-x86_64: warning: TCG doesn't support requested feature: CPUID.07H:EBX.rtm [bit 11]
qemu-x86_64: warning: TCG doesn't support requested feature: CPUID.07H:EBX.avx512f [bit 16]
qemu-x86_64: warning: TCG doesn't support requested feature: CPUID.07H:EBX.avx512dq [bit 17]
qemu-x86_64: warning: TCG doesn't support requested feature: CPUID.07H:EBX.avx512cd [bit 28]
qemu-x86_64: warning: TCG doesn't support requested feature: CPUID.07H:EBX.avx512bw [bit 30]
qemu-x86_64: warning: TCG doesn't support requested feature: CPUID.07H:EBX.avx512vl [bit 31]
qemu-x86_64: warning: TCG doesn't support requested feature: CPUID.0DH:EAX.xsavec [bit 1]
Illegal instruction (core dumped)
```

**Comment by dElogics** [comment]
Confirmed with 9.1.2
